WITH MenuTree AS (
    SELECT ID, ID_MENU, NAME_MENU, SHOWING_LABEL, TYPE_MENU, CHILD_MENU, IS_ACTIVATED, 0 AS Level
    FROM MASTER_FUNCTION
    WHERE CHILD_MENU = 0

    UNION ALL

    SELECT m.ID, m.ID_MENU, m.NAME_MENU, m.SHOWING_LABEL, m.TYPE_MENU, m.CHILD_MENU, m.IS_ACTIVATED, mt.Level + 1
    FROM MASTER_FUNCTION m
    INNER JOIN MenuTree mt ON m.CHILD_MENU = mt.ID
)
SELECT * FROM MenuTree
-- WHERE CHILD_MENU > 0 AND Level > 0
ORDER BY ID_MENU, Level, NAME_MENU;


--SELECT * FROM MASTER_FUNCTION

--UPDATE MASTER_FUNCTION SET NAME_MENU='Holiday List' WHERE ID=4